Actualizacion de temas bloque 3
wizelineacademy/BAZiOS3-2022 pull request #1
Opened 2022-11-17 18:22 UTC by jorge-benavides

2022-11-18 14:10 UTC, abner-castro requested changes
Algunos cambios menores

2022-11-18 14:10 UTC, abner-castro commented on README.md
> +- Martes y Jueves: 2pm en oficinas de Wizeline - [Liga zoom](TODO:) en caso de no poderse presentar
Pero ahora será lunes y martes, no?

2022-11-18 14:10 UTC, abner-castro commented on README.md
> +| ID Empleado | Nombre                  | Mentor                                                    |
Igual aquí un TODO para los nuevos mentores que se añadan

2022-11-18 14:10 UTC, abner-castro commented on curso/semana_3/sesion_2/README.md
> +## UKit
poner arcoiris aquí jaja

2022-11-18 19:17 UTC, jorge-benavides commented on README.md
> +- Martes y Jueves: 2pm en oficinas de Wizeline - [Liga zoom](TODO:) en caso de no poderse presentar
Seguro si, en el rebase no supe cual era el mas reciente

2022-11-18 19:20 UTC, jorge-benavides commented on README.md
> +| ID Empleado | Nombre                  | Mentor                                                    |
✅

2022-11-18 19:20 UTC, jorge-benavides commented on curso/semana_3/sesion_2/README.md
> +## UKit
✅

2022-11-18 19:36 UTC, abner-castro commented on README.md
> +- Martes y Jueves: 2pm en oficinas de Wizeline - [Liga zoom](TODO:) en caso de no poderse presentar
Sí el de lunes y martes

2022-11-22 20:11 UTC, abner-castro approved these changes

2022-11-22 20:11 UTC, abner-castro commented
You can merge it safely :)

2022-11-22 22:04 UTC, merged