Add exercises for week 3 sessions 2 and 3
wizelineacademy/BAZiOS3-2022 pull request #9
Opened 2023-01-26 17:52 UTC by themem12

2023-02-01 22:00 UTC, jorge-benavides requested changes

2023-02-01 22:00 UTC, jorge-benavides commented on curso/semana_3/sesion_2/README.md
> +    - Clona el repositorio TODO.
Proporciona la url del playground o repo eg.
`[Patrones de diseño](curso/semana_3/sesion_2/design-patterns-exercises-main/)`

2023-02-01 22:00 UTC, jorge-benavides commented on curso/semana_3/sesion_3/README.md
> +    - Descarga el proyecto 'RefactorMVVM'.
Ditto. 
Igual proporciona la url al RefactorMVVM

2023-02-01 22:11 UTC, themem12 commented on curso/semana_3/sesion_3/README.md
> +    - Descarga el proyecto 'RefactorMVVM'.
Hola Jorge, en el mismo commit estoy mandando los archivos, necesito que se suban para poder sacar la url y agregarla en cada sección.

2023-02-01 22:30 UTC, jorge-benavides commented on curso/semana_3/sesion_3/README.md
> +    - Descarga el proyecto 'RefactorMVVM'.
Te puse un ejemplo. Usando la url relativa del archivo/directorio

2023-02-02 07:09 UTC, themem12 commented on curso/semana_3/sesion_3/README.md
> +    - Descarga el proyecto 'RefactorMVVM'.
Listo ya quedó el link, hice unas cuantas pruebas por eso los cambios, quedo al pendiente

2023-02-09 00:37 UTC, jorge-benavides approved these changes

2023-02-09 01:42 UTC, merged